### ISSUE TITLE
Only spinning wheel where canvas should be

### ISSUE THREAD

**Issue by Ultomato** [florian-rieder/gutenbergp5#2]
Hello! I am trying to use this plugin (v1.1.1) in WordPress 6.5.2. I didn't notice any complaints when I installed it. Most of my site is built using Divi, but I started a new page that uses the default block editor (Gutenburg I assume). I am able to add a p5.js block. Even with the simplest sketch, I get a spinning wheel on the page. Any suggestions on how to resolve?
See my demo page here: [https://planyukon.ca/easy-p5-demo/](https://planyukon.ca/easy-p5-demo/).
![Easy_p5_wheel](https://github.com/florian-rieder/gutenbergp5/assets/167120395/5b880b12-f069-4d56-adbd-750f7930a1ff)

**Comment by florian-rieder** [comment]
Hi there,

Thanks for reaching out. It seems like there might be a conflict with another plugin affecting iframes on your site.

Could you share a list of the plugins you're using? This will help us identify the issue and find a solution.

I didn't implement any spinning wheel functionality, so it's likely an external factor causing this, for instance an optimization plugin.

Looking forward to your response so we can troubleshoot your issue.

Best regards,
Florian

**Comment by Ultomato** [comment]
Hi Florian,

Thanks for replying so quickly. I've attached screenshots of all the plug-ins for our website. I'll go through them now and deactivate each one to see what happens - trial and error style. I'll let you know what I find. Let me know if you have any insights.

Since we are corresponding, I have one comment and one question:

Comment: the p5.js sketch editor in your codeblock renders really narrow on my backend. Have you seen this? Ideas for how to fix? See screenshot.

Question: does your codeblock work with Divi? If so, how? If not, is this something you would be interested in developing? I don't have a sense in how much work that would be, but may be able to pay if not too big.

Thanks!

Sam
![Screenshot 2024-04-16 120953](https://github.com/florian-rieder/gutenbergp5/assets/167120395/75fd4a9b-6b87-40fe-a9b1-714cc5b9e603)
![Narrow_sketch editor](https://github.com/florian-rieder/gutenbergp5/assets/167120395/2f8c8e38-813e-4f59-b87e-493a13b898ba)
![Screenshot 2024-04-16 121617](https://github.com/florian-rieder/gutenbergp5/assets/167120395/53d3d7d4-1b66-4f7f-8063-99c1c878d8b1)
![Screenshot 2024-04-16 121119](https://github.com/florian-rieder/gutenbergp5/assets/167120395/27aafb7c-c0f8-419e-bca7-5deb19c8b44c)
![Screenshot 2024-04-16 121030](https://github.com/florian-rieder/gutenbergp5/assets/167120395/ce05b95f-eed4-45dc-9c93-cdc579da2e48)
![Screenshot 2024-04-16 121010](https://github.com/florian-rieder/gutenbergp5/assets/167120395/0a93032b-3c42-4767-8b3e-c0566bc18018)


PS: This is for my work website. I am personally interested in developing my own website for my generative art. I was interested in seeing yours!

**Comment by Ultomato** [comment]
Good news! When I deactivated the first plugin (a3 Lazy Load), your plugin started working and nothing really broke. I continued experimenting by starting a Divi editing session with a page built earlier with Gutenberg with your plugin. I then saved it in the Divi module library. I then used Divi to put that module into a new part of the page, and it worked (though it isn't rendered in the editor page, I can see the underlying code)!

So I think I'm free to polish my sketch, save as a divi module then use throughout my site. Thanks for the great module and quick feedback!

**Comment by florian-rieder** [comment]
Hello Sam,

Thank you for the kind words, and I'm glad that you were able to find a solution ! I was indeed suspecting a lazy loading feature to be the reason for the issue. But there is no reason _a priori_, for such a feature to break the sketch, so I would say that it is a bug in a3 Lazy Load as you have noted. If you still want lazy loading, maybe try a few other plugins which lazy load iframes and see if the issue persists.

From what I've read, Divi offers some level of compatibility with Gutenberg by default. Since I have no experience working with Divi, and you seem to have found a satisfying solution, we'll say that, yes, this plugin is compatible with Divi ;)

As for the code editor not taking up the full width, this seems to have been caused by a recent WordPress update. Thank you for bringing this to my attention. I will get around to fixing it at some point ! I hope sooner than later, but this is not really a breaking bug, so I'll add it to my backlog ! I generally recommend to do the actual coding in your preferred IDE, and paste the code into the block's editor anyway, although I understand this is a limitation.

Thanks again for using the plugin,
Cheers,
Florian

PS: You can find some of my artworks on my [personal website](https://florianrieder.com/adding-p5-js-to-wordpress/) (although I havent updated it in a bit), and on the [site for my most recent project](https://florian-rieder.github.io/generative-experiments/). I appreciate your interest !
